services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    restart: unless-stopped

  containrx:
    build:
      context: https://github.com/shaasium/containrx-server.git#main
      dockerfile: Dockerfile
    container_name: containrx-server
    ports:
      - ${CONTAINRX_EXPOSE_PORT}:${CONTAINRX_EXPOSE_PORT}
    environment:
      - CONTAINRX_EXPOSE_PORT=${CONTAINRX_EXPOSE_PORT}
      - MONGO_URI=mongodb://mongodb:27017/containrx
      - SECRET_KEY=${SECRET_KEY}
      - DOCKER_ENGINE_URL=${DOCKER_ENGINE_URL}
    depends_on:
      - mongodb
    restart: unless-stopped

  containrx-dashboard:
    build:
      context: https://github.com/shaasium/containrx-dashboard.git#main
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_BACKEND_URL=http://containrx:${CONTAINRX_EXPOSE_PORT}
    container_name: containrx-dashboard
    ports:
      - 3000:3000
    depends_on:
      - containrx
    restart: unless-stopped

volumes:
  mongodb-data:

networks:
  default:
    name: containrx-network
